name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            computorv1/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('computorv1/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        working-directory: ./computorv1
        run: cargo build --verbose

      - name: Run tests
        working-directory: ./computorv1
        run: cargo test --verbose

      - name: Run Clippy
        working-directory: ./computorv1
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check code formatting
        working-directory: ./computorv1
        run: cargo fmt --all -- --check
